# Generated by Django 3.2.20 on 2023-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='webhook_event_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
